Delegate #strftime to @time in local date and time objects
fbernier/tomlrb pull request #39
Opened 2021-01-08 18:59 UTC by itsliamegan

I need to give a "user" (developer) the result of a parsed TOML document, and in particular they often need to use the Date/Time #strftime method. Several methods are already delegated to @time, so I just added #strftime to create even more synergy between the built-ins and the custom TOML classes for dates and times.

2021-01-14 14:55 UTC, KitaitiMakoto approved these changes

2021-01-14 15:20 UTC, KitaitiMakoto requested changes
Sorry, I approved by mistake.

`#strftime` does not have meaning for those classes. Each class has some fake attributes in its internal `Time` object. For instance, "`LocalTime`'s year, month, day and timezone" has no meaning, and they should not be formatted.

If you need `#strftime`, IMO, it should be implemented so that it formats only, in the `LocalTime`'s case, hours, minutes, seconds and milliseconds.

2021-01-19 20:02 UTC, itsliamegan commented
That's a good point, I hadn't thought about how certain fields don't have meaning for the various types. Given that, I don't think `#strftime` even makes sense, because you'd expect to be able to use all the format strings but would get errors when using things that the object doesn't have, which isn't intuitive.

Closing as adding it would be more complexity than it's worth. I'll expose formatting in some different way for my use case 👍

2021-01-19 20:02 UTC, closed without merging

2021-01-20 10:25 UTC, KitaitiMakoto commented
I hope `#to_time` method of each class helps you and your users.